"""Initial migration

Revision ID: 22301048915d
Revises: 
Create Date: 2025-03-02 20:42:10.938525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22301048915d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv',
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', 'timeframe', 'timestamp', name='uix_ohlcv')
    )
    op.create_index(op.f('ix_ohlcv_exchange'), 'ohlcv', ['exchange'], unique=False)
    op.create_index('ix_ohlcv_query', 'ohlcv', ['exchange', 'symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ohlcv_symbol'), 'ohlcv', ['symbol'], unique=False)
    op.create_index(op.f('ix_ohlcv_timeframe'), 'ohlcv', ['timeframe'], unique=False)
    op.create_index(op.f('ix_ohlcv_timestamp'), 'ohlcv', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('strategy_parameters', sa.JSON(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_loss_percent', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_exchange'), 'trades', ['exchange'], unique=False)
    op.create_index(op.f('ix_trades_position_id'), 'trades', ['position_id'], unique=False)
    op.create_index('ix_trades_query', 'trades', ['exchange', 'symbol', 'position_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_trades_side'), 'trades', ['side'], unique=False)
    op.create_index(op.f('ix_trades_strategy'), 'trades', ['strategy'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy'), table_name='trades')
    op.drop_index(op.f('ix_trades_side'), table_name='trades')
    op.drop_index('ix_trades_query', table_name='trades')
    op.drop_index(op.f('ix_trades_position_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_exchange'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_ohlcv_timestamp'), table_name='ohlcv')
    op.drop_index(op.f('ix_ohlcv_timeframe'), table_name='ohlcv')
    op.drop_index(op.f('ix_ohlcv_symbol'), table_name='ohlcv')
    op.drop_index('ix_ohlcv_query', table_name='ohlcv')
    op.drop_index(op.f('ix_ohlcv_exchange'), table_name='ohlcv')
    op.drop_table('ohlcv')
    # ### end Alembic commands ### 