"""Initial migration

Revision ID: 6e3e15a2f1f0
Revises: 
Create Date: 2025-03-10 19:34:41.388411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3e15a2f1f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_history',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_history_run_id'), 'configuration_history', ['run_id'], unique=False)
    op.create_index(op.f('ix_configuration_history_timestamp'), 'configuration_history', ['timestamp'], unique=False)
    op.create_table('cryptocurrencies',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('avg_daily_volume', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exchange_specific_id', sa.String(length=50), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uix_crypto_symbol')
    )
    op.create_index(op.f('ix_cryptocurrencies_symbol'), 'cryptocurrencies', ['symbol'], unique=True)
    op.create_table('performance_metrics',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_profit_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_run_id'), 'performance_metrics', ['run_id'], unique=False)
    op.create_index(op.f('ix_performance_metrics_timestamp'), 'performance_metrics', ['timestamp'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ohlcv', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('order_book', sa.JSON(), nullable=False),
    sa.Column('trading_volume', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('market_sentiment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('correlation_btc', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cryptocurrency_id', 'timestamp', name='uix_market_snapshot_crypto_time')
    )
    op.create_index(op.f('ix_market_snapshots_cryptocurrency_id'), 'market_snapshots', ['cryptocurrency_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_symbol'), 'market_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_snapshots_timestamp'), 'market_snapshots', ['timestamp'], unique=False)
    op.create_table('ohlcv',
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', 'timeframe', 'timestamp', name='uix_ohlcv')
    )
    op.create_index(op.f('ix_ohlcv_cryptocurrency_id'), 'ohlcv', ['cryptocurrency_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_exchange'), 'ohlcv', ['exchange'], unique=False)
    op.create_index('ix_ohlcv_query', 'ohlcv', ['exchange', 'symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ohlcv_symbol'), 'ohlcv', ['symbol'], unique=False)
    op.create_index(op.f('ix_ohlcv_timeframe'), 'ohlcv', ['timeframe'], unique=False)
    op.create_index(op.f('ix_ohlcv_timestamp'), 'ohlcv', ['timestamp'], unique=False)
    op.create_table('positions',
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('position_type', sa.Enum('LONG', 'SHORT', name='positiontype'), nullable=False),
    sa.Column('stop_loss_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('take_profit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_CLOSED', 'CLOSED', name='positionstatus'), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('profit_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('profit_loss_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('strategy_used', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_cryptocurrency_id'), 'positions', ['cryptocurrency_id'], unique=False)
    op.create_index(op.f('ix_positions_entry_timestamp'), 'positions', ['entry_timestamp'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('partial_exits',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exit_percentage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('trailing_stop_activated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partial_exits_position_id'), 'partial_exits', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partial_exits_position_id'), table_name='partial_exits')
    op.drop_table('partial_exits')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_entry_timestamp'), table_name='positions')
    op.drop_index(op.f('ix_positions_cryptocurrency_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_ohlcv_timestamp'), table_name='ohlcv')
    op.drop_index(op.f('ix_ohlcv_timeframe'), table_name='ohlcv')
    op.drop_index(op.f('ix_ohlcv_symbol'), table_name='ohlcv')
    op.drop_index('ix_ohlcv_query', table_name='ohlcv')
    op.drop_index(op.f('ix_ohlcv_exchange'), table_name='ohlcv')
    op.drop_index(op.f('ix_ohlcv_cryptocurrency_id'), table_name='ohlcv')
    op.drop_table('ohlcv')
    op.drop_index(op.f('ix_market_snapshots_timestamp'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_symbol'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_cryptocurrency_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_performance_metrics_timestamp'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_run_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_cryptocurrencies_symbol'), table_name='cryptocurrencies')
    op.drop_table('cryptocurrencies')
    op.drop_index(op.f('ix_configuration_history_timestamp'), table_name='configuration_history')
    op.drop_index(op.f('ix_configuration_history_run_id'), table_name='configuration_history')
    op.drop_table('configuration_history')
    # ### end Alembic commands ### 